name: Create Tag
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # Ceci est necessaire car l'utilisateur par default du workflow, ne DECLENCHE PAS les actions
      - name: Setup git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email ""
      - name: Set up java/maven       
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - run: |
          mvn -Dmaven.test.skip=true --batch-mode release:prepare
          git push origin main --tags
